export const reducerCases = {
  SET_USER_INFO: "SET_USER_INFO",
  SET_NEW_USER: "SET_NEW_USER",
  SET_ALL_CONTACTS_PAGE: "SET_ALL_CONTACTS_PAGE",
  CHANGE_CURRENT_CHAT_USER: "CHANGE_CURRENT_CHAT_USER",
  SET_MESSAGES: "SET_MESSAGES",
  SET_SOCKET: "SET_SOCKET",
  ADD_MESSAGE: "ADD_MESSAGE",
  ADD_MESSAGES_BOTTOM: "ADD_MESSAGES_BOTTOM",
  ADD_MESSAGES_TOP:"ADD_MESSAGES_TOP",
  SET_MESSAGE_SEARCH: "SET_MESSAGE_SEARCH",
  SET_ONLINE_USERS: "SET_ONLINE_USERS",
  SET_CONTACTS: "SET_CONTACTS",
  SET_CONTACTS_SEARCH: "SET_CONTACTS_SEARCH",
  SET_VIDEO_CALL: "SET_VIDEO_CALL",
  SET_VOICE_CALL: "SET_VOICE_CALL",
  END_CALL: "END_CALL",
  SET_EXIT_CHAT: "SET_EXIT_CHAT",
  SET_INCOMING_VOICE_CALL: "SET_INCOMING_VOICE_CALL",
  SET_INCOMING_VIDEO_CALL: "SET_INCOMING_VIDEO_CALL",
  //UPDATE LAST MESSAGE
  UPDATE_LAST_MESSAGE: "UPDATE_LAST_MESSAGE",
  // SEEN_DELIVERED_SINGLE_MESSAGE
  SEEN_MESSAGE_STATUS: "SEEN_MESSAGE_STATUS",
  DELIVERED_MESSAGE_STATUS: "DELIVERED_MESSAGE_STATUS",

  // SEEN/DELIVERED_ALL_MESSAGES
  ALL_MESSAGE_STATUS_SEEN: "ALL_MESSAGE_STATUS_SEEN",
  ALL_MESSAGE_STATUS_DELIVERED: "ALL_MESSAGE_STATUS_DELIVERED",
};
